name: Build and Deploy to Azure Web App

on:
  push:
    branches: [ main ]

env:
  DOTNET_VERSION: '9.0.x'
  WORKING_DIRECTORY: './MyWeb'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.WORKING_DIRECTORY }}
      
    - name: Build and publish
      run: dotnet publish --configuration Release --output ./publish
      working-directory: ${{ env.WORKING_DIRECTORY }}
      
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.WORKING_DIRECTORY }}/publish
